version: '3.8'

services:
  db:
    image: mysql:8.0.22
    restart: always
    environment:
      - MYSQL_DATABASE=forbys
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/:/docker-entrypoint-initdb.d
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-filesystem=utf8mb4 --lower-case-table-names=0

  spring:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005
    env_file:
      - .env
    networks:
      - backend-network

volumes:
  mysql_data:
networks:
  backend-network: