apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    chart: {{- include "helm-spring-app.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
    run: spring
spec:
  type: {{ .Values.service.type }}
  selector:
    run: spring
  ports:
    - name: https
      port: 80
      targetPort: 8080
      protocol: TCP
