name: CI

on:
  push:
    branches: [master, dev]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Copy environment-specific properties
        run: cp src/main/resources/application-dev.properties src/main/resources/application.properties;
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with Gradle
        run: ./gradlew build -Pprofile=dev

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag odrakir1/forbys-be:latest --build-arg SPRING_PROFILES_ACTIVE=dev
          docker push odrakir1/forbys-be:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: "Connect to VPS"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            whoami
            kubectl get nodes

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy Helm Chart into VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "spring-app/"
          target: /home/${{ secrets.VPS_USERNAME }}/
      
      - name: Deploy with Helm
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export KUBECONFIG=/home/${{ secrets.VPS_USERNAME }}/.kube/config
            helm upgrade --install spring-app ./spring-app --namespace dev --set image.repository=odrakir1/forbys-be --set image.tag=latest

